// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/example.proto

#include "tensorflow/core/example/example.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace tensorflow {
PROTOBUF_CONSTEXPR Example::Example(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.features_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ExampleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExampleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExampleDefaultTypeInternal() {}
  union {
    Example _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExampleDefaultTypeInternal _Example_default_instance_;
PROTOBUF_CONSTEXPR SequenceExample::SequenceExample(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.context_)*/nullptr
  , /*decltype(_impl_.feature_lists_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SequenceExampleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SequenceExampleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SequenceExampleDefaultTypeInternal() {}
  union {
    SequenceExample _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SequenceExampleDefaultTypeInternal _SequenceExample_default_instance_;
}  // namespace tensorflow
static ::_pb::Metadata file_level_metadata_tensorflow_2fcore_2fexample_2fexample_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_tensorflow_2fcore_2fexample_2fexample_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_tensorflow_2fcore_2fexample_2fexample_2eproto = nullptr;

const uint32_t TableStruct_tensorflow_2fcore_2fexample_2fexample_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tensorflow::Example, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tensorflow::Example, _impl_.features_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tensorflow::SequenceExample, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tensorflow::SequenceExample, _impl_.context_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::SequenceExample, _impl_.feature_lists_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::tensorflow::Example)},
  { 7, -1, -1, sizeof(::tensorflow::SequenceExample)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::tensorflow::_Example_default_instance_._instance,
  &::tensorflow::_SequenceExample_default_instance_._instance,
};

const char descriptor_table_protodef_tensorflow_2fcore_2fexample_2fexample_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n%tensorflow/core/example/example.proto\022"
  "\ntensorflow\032%tensorflow/core/example/fea"
  "ture.proto\"1\n\007Example\022&\n\010features\030\001 \001(\0132"
  "\024.tensorflow.Features\"i\n\017SequenceExample"
  "\022%\n\007context\030\001 \001(\0132\024.tensorflow.Features\022"
  "/\n\rfeature_lists\030\002 \001(\0132\030.tensorflow.Feat"
  "ureListsB\201\001\n\026org.tensorflow.exampleB\rExa"
  "mpleProtosP\001ZSgithub.com/tensorflow/tens"
  "orflow/tensorflow/go/core/example/exampl"
  "e_protos_go_proto\370\001\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_deps[1] = {
  &::descriptor_table_tensorflow_2fcore_2fexample_2ffeature_2eproto,
};
static ::_pbi::once_flag descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto = {
    false, false, 388, descriptor_table_protodef_tensorflow_2fcore_2fexample_2fexample_2eproto,
    "tensorflow/core/example/example.proto",
    &descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_once, descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_tensorflow_2fcore_2fexample_2fexample_2eproto::offsets,
    file_level_metadata_tensorflow_2fcore_2fexample_2fexample_2eproto, file_level_enum_descriptors_tensorflow_2fcore_2fexample_2fexample_2eproto,
    file_level_service_descriptors_tensorflow_2fcore_2fexample_2fexample_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_getter() {
  return &descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tensorflow_2fcore_2fexample_2fexample_2eproto(&descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto);
namespace tensorflow {

// ===================================================================

class Example::_Internal {
 public:
  static const ::tensorflow::Features& features(const Example* msg);
};

const ::tensorflow::Features&
Example::_Internal::features(const Example* msg) {
  return *msg->_impl_.features_;
}
void Example::clear_features() {
  if (GetArenaForAllocation() == nullptr && _impl_.features_ != nullptr) {
    delete _impl_.features_;
  }
  _impl_.features_ = nullptr;
}
Example::Example(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tensorflow.Example)
}
Example::Example(const Example& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Example* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.features_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_features()) {
    _this->_impl_.features_ = new ::tensorflow::Features(*from._impl_.features_);
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.Example)
}

inline void Example::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.features_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Example::~Example() {
  // @@protoc_insertion_point(destructor:tensorflow.Example)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Example::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.features_;
}

void Example::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Example::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.Example)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.features_ != nullptr) {
    delete _impl_.features_;
  }
  _impl_.features_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Example::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tensorflow.Features features = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_features(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Example::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.Example)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorflow.Features features = 1;
  if (this->_internal_has_features()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::features(this),
        _Internal::features(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.Example)
  return target;
}

size_t Example::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.Example)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tensorflow.Features features = 1;
  if (this->_internal_has_features()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.features_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Example::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Example::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Example::GetClassData() const { return &_class_data_; }


void Example::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Example*>(&to_msg);
  auto& from = static_cast<const Example&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.Example)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_features()) {
    _this->_internal_mutable_features()->::tensorflow::Features::MergeFrom(
        from._internal_features());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Example::CopyFrom(const Example& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.Example)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example::IsInitialized() const {
  return true;
}

void Example::InternalSwap(Example* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.features_, other->_impl_.features_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Example::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_getter, &descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_once,
      file_level_metadata_tensorflow_2fcore_2fexample_2fexample_2eproto[0]);
}

// ===================================================================

class SequenceExample::_Internal {
 public:
  static const ::tensorflow::Features& context(const SequenceExample* msg);
  static const ::tensorflow::FeatureLists& feature_lists(const SequenceExample* msg);
};

const ::tensorflow::Features&
SequenceExample::_Internal::context(const SequenceExample* msg) {
  return *msg->_impl_.context_;
}
const ::tensorflow::FeatureLists&
SequenceExample::_Internal::feature_lists(const SequenceExample* msg) {
  return *msg->_impl_.feature_lists_;
}
void SequenceExample::clear_context() {
  if (GetArenaForAllocation() == nullptr && _impl_.context_ != nullptr) {
    delete _impl_.context_;
  }
  _impl_.context_ = nullptr;
}
void SequenceExample::clear_feature_lists() {
  if (GetArenaForAllocation() == nullptr && _impl_.feature_lists_ != nullptr) {
    delete _impl_.feature_lists_;
  }
  _impl_.feature_lists_ = nullptr;
}
SequenceExample::SequenceExample(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tensorflow.SequenceExample)
}
SequenceExample::SequenceExample(const SequenceExample& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SequenceExample* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.context_){nullptr}
    , decltype(_impl_.feature_lists_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_context()) {
    _this->_impl_.context_ = new ::tensorflow::Features(*from._impl_.context_);
  }
  if (from._internal_has_feature_lists()) {
    _this->_impl_.feature_lists_ = new ::tensorflow::FeatureLists(*from._impl_.feature_lists_);
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.SequenceExample)
}

inline void SequenceExample::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.context_){nullptr}
    , decltype(_impl_.feature_lists_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SequenceExample::~SequenceExample() {
  // @@protoc_insertion_point(destructor:tensorflow.SequenceExample)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SequenceExample::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.context_;
  if (this != internal_default_instance()) delete _impl_.feature_lists_;
}

void SequenceExample::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SequenceExample::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.SequenceExample)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.context_ != nullptr) {
    delete _impl_.context_;
  }
  _impl_.context_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.feature_lists_ != nullptr) {
    delete _impl_.feature_lists_;
  }
  _impl_.feature_lists_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SequenceExample::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tensorflow.Features context = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_context(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tensorflow.FeatureLists feature_lists = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_feature_lists(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SequenceExample::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.SequenceExample)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorflow.Features context = 1;
  if (this->_internal_has_context()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::context(this),
        _Internal::context(this).GetCachedSize(), target, stream);
  }

  // .tensorflow.FeatureLists feature_lists = 2;
  if (this->_internal_has_feature_lists()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::feature_lists(this),
        _Internal::feature_lists(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.SequenceExample)
  return target;
}

size_t SequenceExample::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.SequenceExample)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tensorflow.Features context = 1;
  if (this->_internal_has_context()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.context_);
  }

  // .tensorflow.FeatureLists feature_lists = 2;
  if (this->_internal_has_feature_lists()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.feature_lists_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SequenceExample::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SequenceExample::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SequenceExample::GetClassData() const { return &_class_data_; }


void SequenceExample::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SequenceExample*>(&to_msg);
  auto& from = static_cast<const SequenceExample&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.SequenceExample)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_context()) {
    _this->_internal_mutable_context()->::tensorflow::Features::MergeFrom(
        from._internal_context());
  }
  if (from._internal_has_feature_lists()) {
    _this->_internal_mutable_feature_lists()->::tensorflow::FeatureLists::MergeFrom(
        from._internal_feature_lists());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SequenceExample::CopyFrom(const SequenceExample& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.SequenceExample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SequenceExample::IsInitialized() const {
  return true;
}

void SequenceExample::InternalSwap(SequenceExample* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SequenceExample, _impl_.feature_lists_)
      + sizeof(SequenceExample::_impl_.feature_lists_)
      - PROTOBUF_FIELD_OFFSET(SequenceExample, _impl_.context_)>(
          reinterpret_cast<char*>(&_impl_.context_),
          reinterpret_cast<char*>(&other->_impl_.context_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SequenceExample::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_getter, &descriptor_table_tensorflow_2fcore_2fexample_2fexample_2eproto_once,
      file_level_metadata_tensorflow_2fcore_2fexample_2fexample_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace tensorflow
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tensorflow::Example*
Arena::CreateMaybeMessage< ::tensorflow::Example >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorflow::Example >(arena);
}
template<> PROTOBUF_NOINLINE ::tensorflow::SequenceExample*
Arena::CreateMaybeMessage< ::tensorflow::SequenceExample >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorflow::SequenceExample >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
